# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4865f483dcc08bdbf2e5df91afa4711377e4119c40dc91eef736b89b1eef7f51025c1b3b4f40ec724aabfda0368807def7385f55426f0ddbe151b08e18d62ee8

test:
  secret_key_base: 9e8fb29df2f99b99c588d8a92cee391cb6d7507a4ecb6070229867ab3b6b0575943446eff50baeed8f6ffb5d7e9e816ea010cf6ff44e696cf8be2a6dac276bb2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
